In [1]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13.csv')

# Учтите, что cols2drop в тестовой системе будет иметь другие значения.
cols2drop = ['ride_cost', 'stop_times', 'user_ride_quality']

# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13_ans.csv', index_col=0)

In [2]:
df.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,ride_cost,speed_avg,speed_max,stop_times,distance,refueling,user_ride_quality,deviation_normal
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,275,87,125.463335,0,2930.798145,0,-11.132653,-8.683
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,202,36,63.275887,0,472.946034,0,-28.508294,-37.196
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,60,47,73.000000,0,283.626484,0,-0.203089,3.378
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,154,31,76.838507,1,100.743738,0,0.219071,14.758
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,163,26,53.000000,1,268.451947,0,15.763025,21.179

In [3]:
# assign flags based on rating and speed_max
df['flag'] = 'undefined'
cond_good = (df['rating'] > 5) & (df['speed_max'] < 100)
cond_bad = (df['rating'] > 5) & (df['speed_max'] > 100)
df.loc[cond_good, 'flag'] = 'good_line'
df.loc[cond_bad, 'flag'] = 'bad_line'
df.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,ride_cost,speed_avg,speed_max,stop_times,distance,refueling,user_ride_quality,deviation_normal,flag
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,275,87,125.463335,0,2930.798145,0,-11.132653,-8.683,undefined
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,202,36,63.275887,0,472.946034,0,-28.508294,-37.196,undefined
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,60,47,73.000000,0,283.626484,0,-0.203089,3.378,undefined
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,154,31,76.838507,1,100.743738,0,0.219071,14.758,undefined
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,163,26,53.000000,1,268.451947,0,15.763025,21.179,undefined

In [4]:
df["speed_check"] = "avg_less"
value = (df["speed_avg"] < df["distance"] / df["ride_duration"])
df.loc[value, "speed_check"] = "avg_more"
df.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,ride_cost,speed_avg,speed_max,stop_times,distance,refueling,user_ride_quality,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,275,87,125.463335,0,2930.798145,0,-11.132653,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,202,36,63.275887,0,472.946034,0,-28.508294,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,60,47,73.000000,0,283.626484,0,-0.203089,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,154,31,76.838507,1,100.743738,0,0.219071,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,163,26,53.000000,1,268.451947,0,15.763025,21.179,undefined,avg_less

In [5]:
df.drop(columns=cols2drop, inplace=True)

In [6]:
df.dropna(subset=['car_id'], inplace=True)

In [7]:
result = df

In [8]:
ans.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,speed_avg,speed_max,distance,refueling,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,87,125.463335,2930.798145,0,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,36,63.275887,472.946034,0,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,47,73.000000,283.626484,0,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,31,76.838507,100.743738,0,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,26,53.000000,268.451947,0,21.179,undefined,avg_less

In [9]:
result.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,speed_avg,speed_max,distance,refueling,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,87,125.463335,2930.798145,0,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,36,63.275887,472.946034,0,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,47,73.000000,283.626484,0,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,31,76.838507,100.743738,0,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,26,53.000000,268.451947,0,21.179,undefined,avg_less

In [10]:
ans.equals(result)

True